import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import {
  Avatar,
  Box,
  Button,
  CircularProgress,
  IconButton,
  Paper,
  Typography,
} from '@mui/material';
import { onAuthStateChanged } from 'firebase/auth';
import useAuth from '@/hooks/useAuth';
import defaultAvatar from '@/assets/images/defaultAvatar.png';
import SettingsIcon from '@mui/icons-material/Settings';
import { ModalJoin } from '@/components/home/ModalJoin';
import useDatabase from '@/hooks/useDatabase';
import { LoadingButton } from '@mui/lab';
import useUser from '@/hooks/useUser';
import useRoom from '@/hooks/useRoom';
import LoadingComponent from '@/components/common/LoadingComponent';
import ChangeAvatarModal from '@/components/common/ChangeAvatar';

export default function Home() {
  const { getUserAndSetUserApp } = useDatabase();
  const { auth, router } = useAuth();
  const { currentUserApp } = useUser();
  const [openCreateModal, setOpenCreateModal] = useState<boolean>(false);
  const [openChangeAvatarModal, setOpenChangeAvatarModal] =
    useState<boolean>(false);
  const {
    createRoom,
    loadingCreate,
    getRoomFromUser,
    loadingRoom,
    leaveRoomFromUser,
    loadingLeave,
  } = useDatabase();
  const { currentRoom } = useRoom();
  const handleClickCreateRoom = () => {
    if (currentUserApp) {
      createRoom(currentUserApp);
    }
  };
  const [loadingRejoin, setLoadingRejoin] = useState<boolean>(false);
  const handleClickRejoin = () => {
    if (currentRoom) {
      setLoadingRejoin(true);
      router.push(`/room/${currentRoom.roomId}`);
    }
  };
  const handleClickLeave = () => {
    if (currentUserApp && currentRoom) {
      leaveRoomFromUser(currentUserApp, currentRoom);
    }
  };
  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      if (user) {
        getUserAndSetUserApp(user);
        if (router.pathname === '/login') {
          router.push('/');
        }
      } else {
        router.push('/login');
      }
    });
    return () => unsub();
  }, []);
  useEffect(() => {
    if (currentUserApp) {
      getRoomFromUser(currentUserApp.roomId);
    }
  }, [currentUserApp]);
  return (
    <>
      <Head>
        <title>Home | Stick Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Paper elevation={24} className={styles.homeContent}>
          <Box className={styles.homeProfile}>
            {currentUserApp ? (
              <>
                <Box className={styles.homeProfileAvatar}>
                  {currentUserApp.photoUrl ? (
                    <Avatar
                      sx={{ width: '150px', height: '150px' }}
                      src={currentUserApp.photoUrl}
                      alt='avatar'
                      variant='square'
                    />
                  ) : (
                    <Avatar
                      sx={{ width: '150px', height: '150px' }}
                      alt='avatar'
                      variant='square'
                    />
                  )}
                  <div
                    onClick={() => {
                      setOpenChangeAvatarModal(true);
                    }}
                    className={styles.homeProfileAvatarButton}
                  >
                    <Typography variant="button">Change Avatar</Typography>
                  </div>
                </Box>
                {/* <Box>
                  <IconButton>
                    <SettingsIcon />
                  </IconButton>
                </Box> */}
                <div className={styles.profileInfo}>
                  <p>{currentUserApp.email}</p>
                </div>
              </>
            ) : (
              <>
                <Box className={styles.homeProfileLoading}>
                  <LoadingComponent />
                  <p>Loading your profile...</p>
                </Box>
              </>
            )}
          </Box>
          <Box className={styles.homeActions}>
            {!loadingRoom ? (
              <>
                {!currentRoom ? (
                  <>
                    <LoadingButton
                      loading={loadingCreate}
                      onClick={handleClickCreateRoom}
                      sx={{ fontSize: '1.2rem' }}
                      variant="contained"
                    >
                      Create Room
                    </LoadingButton>
                    <Button
                      onClick={() => setOpenCreateModal(true)}
                      sx={{ fontSize: '1.2rem' }}
                      variant="contained"
                    >
                      Join Room
                    </Button>{' '}
                  </>
                ) : (
                  <>
                    <Box className={styles.homeRoomInfo}>
                      <p>Your room is: {currentRoom.roomId}</p>
                      <LoadingButton
                        onClick={handleClickRejoin}
                        sx={{ fontSize: '1.2rem' }}
                        variant="contained"
                        loading={loadingRejoin}
                      >
                        Re-join
                      </LoadingButton>
                      <LoadingButton
                        color="error"
                        onClick={handleClickLeave}
                        sx={{ fontSize: '1.2rem' }}
                        variant="contained"
                        loading={loadingLeave}
                      >
                        Leave
                      </LoadingButton>
                    </Box>
                  </>
                )}
              </>
            ) : (
              <>
                <Box className={styles.homeProfileLoading}>
                  <LoadingComponent />
                  <p>Loading your room info...</p>
                </Box>
              </>
            )}
          </Box>
        </Paper>
        <ModalJoin open={openCreateModal} setOpen={setOpenCreateModal} />
        <ChangeAvatarModal
          open={openChangeAvatarModal}
          setOpen={setOpenChangeAvatarModal}
        />
      </main>
    </>
  );
}
export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  };
}
